### ISSUE TITLE
support macOS and move to audiojs org

### ISSUE THREAD

**Issue by derhuerst** [noffle/mic-stream#2]
Hey!

Great to see that someone already wrapped their head around how to get mic PCM data on Linux! **I'd like to contribute macOS support.**

I would also like to add a few best practices:

- license file
- badges to quickly tell if this lib looks promising

For greater visibility, you could transfer the repo to the @audiojs org, which contains many high-quality UNIX-like tools to audio processing.

**Comment by noffle** [comment]
I would :heart: macOS support! I *think* macOS has a built-in `arecord`-like command line tool. Hopefully it's as simple as wrapping it.

License file and badges: sure! Send a PR?

**Comment by ahdinosaur** [comment]
if it's helpful, i wrote [`read-audio`](https://github.com/ahdinosaur/read-audio) which is a similar module that might have re-usable code.

**Comment by derhuerst** [comment]
On my macOS, there's no `arecord` available.

I also got recording working on macOS, using [sox](http://sox.sourceforge.net): `rec -q --channels 2 --bits 16 --rate 44100 --type raw -`. I'm not sure wether to proceed using `arecord` or `rec`, but my goal is to make `mic-stream` full cross-platform and isomorphic. Your `read-audio` will be very helpful in this matter.

**Comment by derhuerst** [comment]
I also found [`microphone-stream`](https://github.com/saebekassebil/microphone-stream/blob/2239b5e/microphone-stream.js), which works in the browser.

**Comment by derhuerst** [comment]
see #8

**Comment by noffle** [comment]
Merged in `1.0.1`.
